#!/bin/bash


if [ "$1" == "help" ]
then
    echo "config -- runs pipenv shell and exports needed python packages"
    echo "naslovnica -- starts naslovnica microservice"
    exit 1
fi

if [ "$1" == "config" ]
then
    export PYTHONPATH="$PYTHONPATH:/config"
    pipenv shell
fi

if [ "$1" == "naslovnica" ]
then
    export PYTHONPATH="$PYTHONPATH:/config"
    python3 ./naslovnica/app.py 3001
fi

if [ "$1" == "onama" ]
then
    export PYTHONPATH="$PYTHONPATH:/config"
    python3 ./o_nama/app.py 3002
fi

if [ "$1" == "natjecaji" ]
then
    export PYTHONPATH="$PYTHONPATH:/config"
    python3 ./natjecaji/app.py 3003
fi

if [ "$1" == "info" ]
then
    export PYTHONPATH="$PYTHONPATH:/config"
    python3 ./informacije/app.py 3004
fi

if [ "$1" == "pymgur" ]
then
    export PYTHONPATH="$PYTHONPATH:/config"
    python3 ./pymgur/app.py 3005
fi

