#!/bin/bash


if [ "$1" == "help" ]
then
    echo "config -- runs pipenv shell and exports needed python packages"
    echo "naslovnica -- starts naslovnica microservice"
    exit 1
fi

if [ "$1" == "config" ]
then
    export PYTHONPATH="$PYTHONPATH:/config"
    pipenv shell
fi




if [ "$1" == "naslovnica" ]
then
    export PYTHONPATH="$PYTHONPATH:/config"
    python3 ./naslovnica/app.py
fi
